import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { CreatePostWizard } from "~/components/CreatePostWizard";

import { Feed } from "~/components/Feed";
import { api } from "~/utils/api";
import { LoadingSpinner } from "~/components/LoadingSpinner";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();

  // Start the query immediately
  api.posts.getAll.useQuery();

  if (!isLoaded)
    return (
      <div className="h-screen">
        <LoadingSpinner size={60} />
      </div>
    );

  return (
    <>
      <Head>
        <title>Emoter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b p-4">
            {!isSignedIn && <SignInButton />}
            {Boolean(isSignedIn) && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
