import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const PostPage: NextPage = () => {
  const params = useRouter();

  return (
    <>
      <Head>
        <title>Emoter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Post View</div>;
    </>
  );
};

export default PostPage;
